version: '3.7'
services:
  dev-server:
    image: node:18.16.1
    container_name: dev-server
    command: sh -c "cd ./app && npm install && npm run dev"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - APP_ENV=${APP_ENV}
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./:/app/
    networks:
      - db-network

  postgres-db: # 서비스 명
    image: postgres:latest # 사용할 이미지
    restart: always
    container_name: postgres # 컨테이너 이름 설정
    networks:
      - db-network
    ports:
      - 5432:5432 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment:
      # PostgreSQL 계정 및 패스워드 설정 옵션
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - /Users/Shared/data/postgres-db:/data/db # -v 옵션 (다렉토리 마운트 설정)

networks:
  db-network:
    driver: bridge
