name: Deploy to ECR

on:
  pull_request:
    branches: ['nocpl']

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR,
        id: build-image
        run: |
          docker build -t hanghae_no_cpl .
          docker tag hanghae_no_cpl:latest 810177324512.dkr.ecr.us-east-1.amazonaws.com/hanghae_no_cpl:latest
          docker push 810177324512.dkr.ecr.us-east-1.amazonaws.com/hanghae_no_cpl:latest
          echo "image=810177324512.dkr.ecr.us-east-1.amazonaws.com/hanghae_no_cpl:latest" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/task-definition.json
          container-name: nocpl-container
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: .aws/task-definition.json
          service: nocplService
          cluster: nocplCluster
          wait-for-service-stability: true
